tl-its-umich-edu/instructor-tools

frontend/components/plasmic/canvas_app_explorer/PlasmicHeader.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHeader.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.css, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.jsx, frontend/package-lock.json, frontend/plasmic.lock
This commit fixes #65 by removing the search tool and settings in the UI until they are implemented. This was done by adding a variant of the header that did not have the search tool and settings icon and enabling the variant. This commit also gives the LearnMore Button a slot.
=> Fixes #65 by Removing Search Functionality in UI

frontend/components/plasmic/canvas_app_explorer/PlasmicAddRemoveButton.css, frontend/components/plasmic/canvas_app_explorer/PlasmicAddRemoveButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.jsx, frontend/plasmic.lock
Fixes up some naming problems (the name of the button slots were very similar to the actual name of each button) and removes the interaction variant from add/remove button.
=> Fixes up some naming problems and removes the interaction variant from add/remove

frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.css, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.jsx, frontend/plasmic.lock
Changed Plasmic to remove LearnMore button from the LearnMore variant of the ProductCard.
=> Updated Plasmic to Remove the LearnMore Button from Variant.

frontend/components/Home.jsx
Updates Home.jsx, so that the code works properly again with the new Plasmic Changes. This includes component name changes, and including LearnMoreSlot in the code.
=> Updates Home.jsx with the new component names and changes in PlasmicHome.jsx

frontend/components/Home.jsx
This pull request addresses issue #14 and #16. Currently able to have add/remove work for all the buttons at once but not each button/tool individually (if user clicks add, it changes for all tools, and if user clicks remove it changes for all tools). Still working on Learn More, it follows a similar idea.
=> Implementing Learn More Button and Add Remove Button.

frontend/components/plasmic/canvas_app_explorer/PlasmicExitLearnMoreButton.css, frontend/components/plasmic/canvas_app_explorer/PlasmicExitLearnMoreButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.css, frontend/plasmic.lock
This pull request modifies the formatting of cards on the webpage so there's not a big space. Also changed the exit button to be an icon.
=> Modified Formatting of Cards on Webpage and Changed Exit Button on Learn More

frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.css, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.jsx, frontend/package-lock.json, frontend/package.json, frontend/plasmic.json, frontend/plasmic.lock
Modified exit button to make the icon look better and clickable. Converted image in learn more card to be a slot to allow for custom images.
=> Modified Exit Button in Learn More and added Custom Images in Learn More

.env.sample, .gitignore, README.md, backend/canvas_app_explorer/admin.py, backend/canvas_app_explorer/apps.py, backend/canvas_app_explorer/models.py, backend/canvas_app_explorer/serializers.py, backend/canvas_app_explorer/views.py, backend/settings.py, backend/urls.py, deploy/supervisor_docker.conf, docker-compose.yml, dockerfiles/Dockerfile, requirements.txt, start_backend.sh, templates/home.html
=> Fixes #84 - Switch runserver to Gunicorn, add migrations to start script

requirements.txt
App was not running, so modified requirements.txt so that it used the latest version of Django 3.2, but would not go to Django 3.3 or beyond.
=> Updated requirements.txt to not use Django 4

frontend/components/plasmic/canvas_app_explorer/PlasmicFooter.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHeader.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHeader.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicLearnMoreButton.css, frontend/components/plasmic/canvas_app_explorer/PlasmicLearnMoreTool.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.css, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicScreenshotBackground.css, frontend/components/plasmic/canvas_app_explorer/plasmic_canvas_app_explorer.css, frontend/components/plasmic/plasmic__default_style.css, frontend/package-lock.json, frontend/package.json, frontend/plasmic.json, frontend/plasmic.lock
This change is done so that the search bar can be referred to as a variable and can be used in the search filter implementation.
=> Updated Plasmic, giving a name to search bar, and including search bar in the header

frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.css, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.jsx, frontend/plasmic.json, frontend/plasmic.lock
This is an automated commit generated by Daniel Zhang
using Plasmic (https://plasmic.app/).
Project name: Canvas App Explorer
Project URL: https://studio.plasmic.app/projects/mXv5TZ5SUPGRneH9RoMn6q
=> Updated Plasmic so that New Learn More Button is in Correct Slot

frontend/components/plasmic/canvas_app_explorer/PlasmicAddRemoveButton.css, frontend/components/plasmic/canvas_app_explorer/PlasmicAddRemoveButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicButton.css, frontend/components/plasmic/canvas_app_explorer/PlasmicButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicExitLearnMoreButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicFooter.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHeader.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHeader.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicIconLink.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicLearnMoreButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicLearnMoreTool.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicLinkButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicMenuButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.css, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicRatings.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicScreenshot.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicScreenshotBackground.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicSearchInputComponent.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicTitleLearnMoreButton.css, frontend/components/plasmic/canvas_app_explorer/PlasmicTitleLearnMoreButton.jsx, frontend/package-lock.json, frontend/package.json, frontend/plasmic.json, frontend/plasmic.lock
Applies Most of the UX changes recommended by UX team after user testing:
- Redesigned learn more card (Changed add button text, uses logo, moved screenshot section, have all the empty space at the bottom of the card)
- Updated learn more button to Find out More
- Moved search filter
- Made buttons clickable
=> Fixes #129 - Applies Most Recommended Changes from UX Testing

frontend/components/plasmic-tokens.theo.json, frontend/components/plasmic/canvas_app_explorer/PlasmicAddRemoveButton.css, frontend/components/plasmic/canvas_app_explorer/PlasmicAddRemoveButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicExitLearnMoreButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicFooter.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHeader.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.css, frontend/components/plasmic/canvas_app_explorer/PlasmicHome.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicIconLink.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicLearnMoreButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicLearnMoreTool.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicLinkButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicMenuButton.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicProductCard.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicRatings.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicScreenshot.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicScreenshotBackground.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicSearchInputComponent.jsx, frontend/components/plasmic/canvas_app_explorer/PlasmicTitleLearnMoreButton.jsx, frontend/components/plasmic/canvas_app_explorer/plasmic_canvas_app_explorer.css, frontend/package-lock.json, frontend/package.json, frontend/plasmic.json, frontend/plasmic.lock
This is an automated commit generated by Matthew Jones
using Plasmic (https://plasmic.app/).
Project name: Canvas App Explorer
Project URL: https://studio.plasmic.app/projects/mXv5TZ5SUPGRneH9RoMn6q
=> [plasmic] Sync project Canvas App Explorer

backend/canvas_app_explorer/serializers.py, backend/canvas_app_explorer/views.py, backend/urls.py
=> Rework `LtiToolViewSet` to prevent multiple API calls (#172)

docker-compose.yml
=> issue #186 update to MySQL v8

backend/canvas_app_explorer/models.py
I changed this class name about 10 times and tested a few different ways. Looks to be the validator pattern for accepting parameters.
=> Fixes #179 - Don't consider HTML formatting in character count limits

frontend/app/components/ToolCard.tsx, frontend/app/components/toolButtons.tsx
This PR aims to resolve #146 and #201.
=> Improve action buttons on `ToolCard` (#146, #201)

frontend/app/components/Home.tsx
=> Use `Snackbar`, update text for refresh alert (#224)

frontend/app/components/ToolCard.tsx, frontend/app/components/toolButtons.tsx
=> Remove duplicate IDs within `ToolCard` (#226)

backend/settings.py
- added 'Source Code' under the Tools dropdown menu
- added Code icon in the navigation tool bar
=> #216 added Source Code option into TinyMCE editor in admin page

frontend/app/components/ToolCard.tsx
=> Add tool name to card under the logo image (#229)

frontend/app/components/ToolCard.tsx
=> Combine Enlarge Screenshot button and image (#228)

.env.sample, backend/canvas_scopes.py, backend/settings.py
=> Provide default Canvas API scopes for OAuth, with an environment variable escape hatch (#202)

backend/canvas_app_explorer/canvas_roles.py, backend/canvas_app_explorer/lti1p3.py, templates/lti_config_template.json
=> Limit access to the tool to course staff (#219, #246)

.env.sample, backend/settings.py, backend/urls.py, requirements.txt
=> Add `django-watchman` status URL

frontend/app/components/ToolCard.tsx
=> Add `role`, `aria-hidden`, and `focusable` values to `CheckCircleOutline` icon (#260)

.env.sample, backend/settings.py, backend/urls.py
=> Fix usage of `django-watchman` (#263)

backend/settings.py
Modified TinyMCE default config in settings to block certain html element and style tags when admin pastes texts into LTI tool card fields.
=> TinyMCE Default Config Modification (#203)

backend/canvas_app_explorer/lti1p3.py
=> Add check for whether deployment ID is included (#272)

backend/settings.py
=> Only ever log canvas_oauth messages with WARN level or higher (#267)

backend/canvas_app_explorer/lti1p3.py
=> #336 updating to warning function

backend/settings.py
=> #357 disable upgrade promotion

Dockerfile, backend/settings.py, deploy/supervisor_docker.conf
Fixes #413 Adding additional logfile config to the main block of supervisor
=> 413 Fix permission denied from supervisor.

backend/settings.py, docker-compose.yml, start_backend.sh
=> docker-compose.yml file cleanup

Dockerfile
=> Hold back build base images to bookworm
